config/routes.rb
TripFollower2::Application.routes.draw do

  devise_for :users

  root to: 'static_pages#home'

  resources :users, only: [:index, :show] do
    resources :user_followings, only: [:create, :destroy]
    member do
      get :followed_users, :followers, :trip_subscriptions
      #get :trip_subscriptions
    end
  end

  resources :trips do
  	resources :trip_administratorings, only: [:create, :destroy]
    resources :trip_whitelistings, only: [:create, :destroy]
    member do
      get :subscribers
      post :subscribe
      delete :unsubscribe
    end
  end

  resources :events, except: [:new, :show]

  resources :instagrams, only: [:show, :index]

  resources :authorizations, only: [:index, :destroy]

  get 'auth/:provider/callback', to: "authorizations#create"
  get 'sandbox', to: 'static_pages#sandbox'
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :name, :tagline, :description, :s_date, :e_date, :hashtag, :whitelist_posters, :public_view

  # Basic Associations
  belongs_to :creator, class_name: "User", foreign_key: :creator_id
  has_many :events, dependent: :destroy
  has_many :trip_administratorings, dependent: :destroy
  has_many :admins, through: :trip_administratorings, source: :user

  # Whitelisting Associations
  has_many :trip_whitelistings, dependent: :destroy
  has_many :whitelisted_users, through: :trip_whitelistings, source: :user

  # Trip Subscription Associations
  has_many :trip_subscriptions, foreign_key: :trip_id
  has_many :subscribed_users, through: :trip_subscriptions, source: :user

  # VALIDATIONS
  validates :name, length: { in: 4..36 }
  validates :name, presence: true
  validates :tagline, length: { maximum: 140 }, allow_blank: true
  validates :description, length: { maximum: 1000 }, allow_blank: true
  validates :hashtag, length: { in: 1..64 }
  validates :hashtag, presence: true

  validate :validate_end_date_after_start_date

  def remove_admin(user)
    self.trip_administratorings.where("user_id = ?", user.id).first.destroy
  end

  def remove_whitelisting(user)
    self.trip_whitelistings.where("user_id = ?", user.id).first.destroy
  end

  def subscribe(user)
    self.trip_subscriptions.create(user: user)
  end

  def subscribe!(user)
    self.trip_subscriptions.create!(user: user)
  end

  def unsubscribe(user)
    self.trip_subscriptions.where("subscriber_id = ?", user.id).first.destroy
  end

  private

  def validate_end_date_after_start_date
    if self.e_date && self.s_date
      if e_date < s_date
        errors.add(:e_date, "End date must be after the start date")
      end
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :trip_admin, only: [:edit, :update]
  before_filter :trip_creator, only: [:destroy]

  def index
    @trips = Trip.limit(30)
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.new(params[:trip])
    if @trip.save
      @trip.trip_administratorings.create!(user: current_user)
      @trip.trip_whitelistings.create!(user: current_user)
      current_user.subscribe_followers_to(@trip)
      flash[:success] = "Your trip has been created!"
      redirect_to @trip
    else
      flash[:error] = "Your trip could not be created"
      render :new
    end
  end

  def show
        @trip = Trip.find(params[:id])
    if request.xhr?
      begin
        if @trip.whitelist_posters
          feed_items = []
          @trip.whitelisted_users.each do |user|
            feed_items += Feed.from_tags_by_user([@trip.hashtag], user)
          end
        else
          feed_items = Feed.from_tags([@trip.hashtag], current_user)
        end
        @feed_items = Feed.sort_feed(feed_items)[0..9] # PAGINATING
      rescue SocketError
        flash.now[:error] = "Could not grab feed media, check your internet connection"
        @feed_items = []
      end
    end

    respond_to do |format|
      format.html
      format.json { render json: @feed_items}
    end
  end

  def edit
    @trip = Trip.includes(:creator).find(params[:id])
    @admins = @trip.admins
    @wl_users = @trip.whitelisted_users
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update_attributes(params[:trip])
      respond_to do |format|
        format.html do
          flash[:success] = "Successfully updated"
          redirect_to @trip
        end
        format.json do
          render json: @trip
        end
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:error] = @trip.errors.full_messages.first
          render :edit
        end
        format.json { render json: { failure: true } }
      end
    end
  end

  def destroy
    trip = Trip.find(params[:id])
    if trip.delete
      flash[:success] = "The trip was successfully deleted"
      redirect_to current_user
    else
      flash[:error] = "The trip could not be deleted"
      redirect_to trip
    end
  end

  def subscribe
    trip = Trip.find(params[:id])
    if trip.subscribe(current_user)
      respond_to do |format|
        format.json { render json: trip }
      end
    else
      respond_to do |format|
        format.json { render json: { failure: true } }
      end
    end
  end

  def unsubscribe
    trip = Trip.find(params[:id])
    if trip.unsubscribe(current_user)
      respond_to do |format|
        format.json { render json: trip }
      end
    else
      respond_to do |format|
        format.json { render json: { failure: true } }
      end
    end
  end

  def subscribers
    @trip = Trip.find(params[:id])
    @subscribers = @trip.subscribed_users
    respond_to do |format|
      format.json { render json: @subscribers }
      format.html { render :subscribers }
    end
  end

  private

    def trip_creator
      trip = current_user.trips.find_by_id(params[:id])
      if trip.nil?
        flash[:error] = "Permission Denied"
        redirect_to root_path
      end
    end

    def trip_admin
      trip = Trip.find_by_id(params[:id])
      unless trip && trip.admins.include?(current_user)
        flash[:error] = "Permission Denied"
        redirect_to root_path
      end
    end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_admin.html.erb
<% if @trip.creator == admin %>
	<li><em><%= admin.username %> (trip creator)</em></li>
<% else %>
	<li id="admin-user-<%= admin.id %>">
		<%= admin.username %> | 
		<a class="remove-admin" data-id=<%= "#{admin.id}" %> >remove</a>
	</li>

<% end %>

app/views/trips/_advanced_settings.html.erb
<% if current_user && current_user.administrates(@trip) %>
  <hr/>
  <h2>Advanced Options:</h2>

  <!-- IS THIS EVIL MODEL CALLING FROM THE VIEW???  -->
  <% if @trip.creator == current_user %> 

    <div id="privacy-and-posting">
      <br />
      <h4>Privacy and Posting:</h4>
      <%= simple_form_for(@trip) do |x| %>
        <div id="trip-view-radio-inputs">
          <%= x.input :public_view, 
                      label: "Public View", 
                      as: :radio_buttons,
                      collection: [['Public', true], ['Private', false]], 
                      disabled: [true, false],
                      hint: 'This option is currently unavailable'  %>
        </div>
        <div id="trip-posting-radio-inputs">
          <%= x.input :whitelist_posters, 
                      label: "Posting", 
                      as: :radio_buttons,
                      collection: [['Public', false], ['Private', true]], 
                      hint: 'Private trips will only allow contributions from "whitelisted" accounts' %>
        </div>
      <% end %>
    </div>

    <div id="trip-admins">
      <h4>Trip Admins:</h4>
      <label for="add-admin">Add Admin</label>
      <input type="text" id="add-admin" placeholder="ExampleUser" />
      <button id="add-admin-button" type="button">Add</button>
      <ul id="admin-list">
        <%= render partial: "admin", collection: @admins %>
      </ul>
    </div>
    <br />

  <% end %>

  <% if @wl_users %>
    <div id="whitelist" <%= @trip.whitelist_posters ? '' : 'style=display:none;' %>>
  <% else %>
    <div style="display:none" id="whitelist">
  <% end %>

    <h4>Whitelist:</h4>
    <p>
      <em>Posts from these users will be pulled into the trip</em>
    </p>
    <label for="add-whitelisted-user">Add to Whitelist</label>
    <input type="text" id="add-whitelisted-user" placeholder="ExampleUser" />
    <button id="add-whitelisted-user-button" type="button">Add</button>
    <ul id="whitelisted-users-list">
      <%= render partial: "whitelisted_user", collection: @wl_users %>
    </ul>

  </div>
  <br />
  <div>
    <%= link_to "<<  Back to Trip", @trip %>
  </div>
<% end %>

app/views/trips/_form.html.erb
<%= simple_form_for(@trip) do |f| %>

  <%= f.input :name,
  						label: "Trip Name",
  						placeholder: 'Bermuda Beaches' %>
  <%= f.input :hashtag,
  						label: "Hashtag",
  						placeholder: 'bermudabeaches' %>
  <%= f.input :tagline,
  						label: "Tagline",
        			placeholder: "Greatest Vacation Ever" %>
  <%= f.input :description,
  						label: "Description",
        			placeholder: 'We put 12 awesome people in a beach house. Epic trip.' %>
  <%= f.input :s_date,
  						label: "Start Date",
              disabled: true,
              hint: "This option hasn't yet been enabled" %>
  <%= f.input :e_date,
  						label: "End Date",
              disabled: true,
              hint: "This option hasn't yet been enabled" %>

  <%= f.button 	:submit,
  							id: "commit",
                class: "btn btn-primary btn-large",
  							value: "Submit" %>

<% end %>

app/views/trips/_trip.html.erb
  <li>

    <% unless current_user == @user %>

      <%= render partial: "shared/trip_subscribe_buttons", locals: { trip: trip } %>

    <% end %>

    <big>
      <%= link_to trip.name, trip_path(trip) %>
    </big>
    <small><em>
      &#35<%= link_to trip.hashtag, "#" %>
    </em></small>

    <% if @user == current_user &&
          @user != trip.creator &&
          trip.admins.include?(current_user) %>
      <span class="admin-indicator">(admin)</span>
    <% end %>

    <% if trip.public_view %>
      | 
      <small>
        <%= render partial: "shared/trip_subscriber_stats", locals: { trip: trip } %>
      </small>
    <% end %>

    <br/>
    <small><em>
      Created on <%= trip.created_at.strftime "%A, %-B %-d, %Y" %>
      by <%= link_to trip.creator.username, trip.creator %>
    </em></small>

  </li>

app/views/trips/_whitelisted_user.html.erb
<% wl_user = whitelisted_user %>
<% if @trip.creator == wl_user %>
	<li><em><%= wl_user.username %> (trip creator)</em></li>
<% else %>
	<li id="whitelisted-user-<%= wl_user.id %>">
		<%= wl_user.username %> | 
		<a class="remove-whitelisted-user" data-id=<%= "#{wl_user.id}" %> >remove</a>
	</li>

<% end %>

app/views/trips/edit.html.erb
<% content_for(:title) { "Trip Settings"} %>
<%= content_tag(:div, id: "admin-url", data: {url: trip_trip_administratorings_url(@trip) } ) {} %>
<%= content_tag(:div, id: "whitelist-url", data: {url: trip_trip_whitelistings_url(@trip) } ) {} %>
<%= content_tag(:div, id: "trip-url", data: {url: trip_url(@trip) } ) {} %>

<div class="offset2">
	<h1>
	  Trip Settings: <%= @trip.name %>
	</h1>
</div>
<div class="row">
	<div class="span8 offset2 panel">
		<p>
			<em>Created by <%= @trip.creator.username %></em>
		</p>

		<%= render partial: 'form' %>
		<br />
		<%= render partial: 'advanced_settings' %>

		<%= javascript_tag do %>
			$(function(){
				TF.AdminLibrary.addAdminListeners();
				TF.WhitelistLibrary.addWhitelistListeners();
				TF.PrivacyAndPostingLibrary.addPrivacyListeners();
			});
		<% end %>
	</div>
</div>

app/views/trips/index.html.erb
<% content_for(:title) { "Trips" } %>

<div class="offset2">
  <h1>
    <%= "All Trips" %>
  </h1>
</div>

<div class="row">
  <div class="span8 offset2 panel">
    <ul class="trips-list">
      <%= render @trips %>
    </ul>
  </div>
</div>

app/views/trips/new.html.erb
  	<% content_for(:title) { "Create Trip"} %>
  <div class="offset2">
  	<h1>
  	  Create a Trip
  	</h1>
  </div>
<div class="row">
  <div class="span8 offset2 panel">

  	<%= render partial: 'form' %>
  </div>
</div>

app/views/trips/show.html.erb
<% content_for(:title) { @trip.name } %>
<%= content_tag(:div, id: "trip-url", data: {url: trip_url(@trip) } ) {} %>

<style>
  body{ background-color: black;}
</style>

<div id="head-box">
  <h1 class="head">
    <%= "#{@trip.name}" %>
    <br>
    <%= render partial: "shared/trip_subscribe_buttons", locals: { trip: @trip } %>
  </h1>
  <div id="loader">
    <%= image_tag 'loader.gif', alt: "loading" %>
  </div>

  <div id="info" class="clear">
    <p>
      <em>Created by <%= link_to "#{@trip.creator.username}", @trip.creator %>
       | <%= render partial: "shared/trip_subscriber_stats", locals: { trip: @trip } %>
      </em>
    </p>
    <% if @trip.whitelist_posters %>
      Whitelisted Users:
      <%= "#{ @trip.whitelisted_users.map(&:username).join(', ')}" %>
    <% end %>

    <% if current_user == @trip.creator %>
      <div>
        <%= link_to "Delete", trip_path(@trip), method: :delete, confirm: "Are you sure you want to delete this trip?" %>
        |
        <%= link_to "Edit", edit_trip_path(@trip) %>
      </div>
    <% elsif current_user && current_user.administrates(@trip)%>
      <div>
        <%= link_to "Edit", edit_trip_path(@trip) %>
      </div>
    <% end %>

    <h3>
      <%= "#{@trip.tagline}"%>
    </h3>
    <p>
      <strong>
        &#35<%= "#{@trip.hashtag}" %>
      </strong>
    </p>
    <p>
      <%= "#{@trip.description}" %>
    </p>
  </div>


</div>

<script>
  $(function(){
    TF.TripShow.getItems(function(){
      TF.TripShow.initializer($("body"));
    });
  });
</script>

app/views/trips/subscribers.html.erb
<% content_for(:title) { "#{@trip.name} Subscribers" } %>

<h1>
  <%= "#{@trip.name} Subscribers" %>
</h1>
<p>
  <em>Created by <%= @trip.creator.username %></em>
   | <%= render partial: "shared/trip_subscriber_stats", locals: { trip: @trip } %>
</p>

<div id="trip-subscribers">

  <%= render @subscribers %>

</div>