config/routes.rb
TripFollower2::Application.routes.draw do

  devise_for :users

  root to: 'static_pages#home'

  resources :users, only: [:index, :show] do
    resources :user_followings, only: [:create, :destroy]
    member do
      get :followed_users, :followers, :trip_subscriptions
      #get :trip_subscriptions
    end
  end

  resources :trips do
  	resources :trip_administratorings, only: [:create, :destroy]
    resources :trip_whitelistings, only: [:create, :destroy]
    member do
      get :subscribers
      post :subscribe
      delete :unsubscribe
    end
  end

  resources :events, except: [:new, :show]

  resources :instagrams, only: [:show, :index]

  resources :authorizations, only: [:index, :destroy]

  get 'auth/:provider/callback', to: "authorizations#create"
  get 'sandbox', to: 'static_pages#sandbox'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :username, :tagline

	before_save { |user| user.email = email.downcase }

  has_many :trips, foreign_key: :creator_id, dependent: :destroy
  has_many :events, foreign_key: :creator_id, dependent: :destroy

  # Admin and Whitelisting Associations
  has_many :trip_adminships, class_name: "TripAdministratoring", foreign_key: :user_id, dependent: :destroy
  has_many :administrated_trips, through: :trip_adminships, source: :trip
  has_many :trip_whitelistings, dependent: :destroy
  has_many :whitelisted_trips, through: :trip_whitelistings,
  		source: :trip

  # User Following Associations
  has_many :user_followings, foreign_key: :follower_id, dependent: :destroy
  has_many :followed_users, through: :user_followings

  has_many :reverse_user_followings, class_name: "UserFollowing", foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :reverse_user_followings, source: :following_user

  # Trip Subscription Associations
  has_many :trip_subscriptions, foreign_key: :subscriber_id
  has_many :subscribed_trips, through: :trip_subscriptions, source: :trip

  # Provider Authorizations
  has_many :authorizations

  # VALIDATIONS
  [ :username, :email ].each do |field| validates field, presence: true
  end
	validates :username, length: { maximum: 24,
					message: "Name lengths must be between 2-24 characters"  }
	validates :username, uniqueness: { case_sensitive: false }

	def administrates(trip) # SHOULD BE QUESTION MARK METHOD
		self.administrated_trips.include?(trip)
	end

	def following?(other_user)
		self.followed_users.include?(other_user)
	end

	def follow!(other_user)
		self.user_followings.create!(followed_id: other_user.id)
    other_user.trips.each do |trip|
      unless self.subscribed_trips.include?(trip)
        trip.subscribe!(self)
      end
    end
	end

	def unfollow!(other_user)
		UserFollowing.find_by_followed_id(other_user.id).destroy
    other_user.trips.each do |trip|
      if self.subscribed_trips.include?(trip)
        trip.unsubscribe(self)
      end
    end
	end

  def subscribed_to?(trip)
    self.subscribed_trips.include?(trip)
  end

  def subscribe_followers_to(trip)
    self.followers.each do |follower|
      unless follower.subscribed_trips.include?(trip)
        trip.subscribe(follower)
      end
    end
  end

  def subscribed_tags
    self.subscribed_trips.map { |trip| trip.hashtag }
  end

  def created_tags
    self.trips.map { |trip| trip.hashtag }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!, except: [:index, :new, :create]
	before_filter :correct_user, only: [:edit, :update, :destroy]


	def index
		@users = User.all
		@followers = current_user.followers if current_user
		@followed_users = current_user.followed_users if current_user
	end

	def show
		@user = User.find(params[:id])
		@followers = @user.followers
		@followed_users = @user.followed_users
		@trips = @user.trips
		@trips_contributed_to = @user.whitelisted_trips.where("trips.creator_id != ?", @user.id).includes(:admins)

		if @user == current_user
			tags = @user.subscribed_tags #+ @user.created_tags
		else
			tags = @user.created_tags
		end

		@feed_items = Feed.from_tags(tags, current_user)

		respond_to do |format|
			format.html
			format.json
		end
	end

	def followers
		@user = User.find(params[:id])
		@followers = @user.followers
	end

	def followed_users
		@user = User.find(params[:id])
		@followed_users = @user.followed_users
	end

	def trip_subscriptions
		@user = User.find(params[:id])
		@subscriptions = @user.subscribed_trips
	end

	def feed
		user = User.find(params[:id])
		tags = ( user == current_user ? user.subscribed_tags : user.created_tags )
		@feed_items = Feed.from_tags(tags)
		respond_to do |format|
			format.html
			format.json
		end
	end

	private

	def correct_user
		redirect_to root_path unless current_user == User.find_by_id(params[:id])
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.user_followings.build(followed_id: @user.id), 
		url: user_user_followings_path(@user.id), remote: true) do |f| %>
	<%= f.hidden_field :followed_id %>
	<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
	<%= f.input :username, label: "User Name", placeholder: 'ExampleUser' %>
	<%= f.input :email, label: "Email Address", placeholder: 'user@example.com' %>
	<%= f.input :password, label: "Password" %>
	<%= f.input :password_confirmation, label: "Confirm Password" %>
	<%= f.button :submit, id: "commit", class: "btn btn-large btn-primary",
	 							value: "Submit" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.followed_users.find(@user.id), url: user_user_following_path(@user.id, current_user), remote: true, method: :delete) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<% if user != current_user %>
  <li>
    <%= render partial: "shared/following_buttons", locals: {user: user } %>
  	<big><%= link_to "#{user.username}", user %></big>
  </li>
<% end %>

app/views/users/_user_following.html.erb
<div id="user-following-sidebar">
	<% unless current_user == @user %>

		<div id="user-following-form">
			<%= render partial: "shared/following_buttons", locals: { user: @user } %>
		</div>

	<% end %>
	<div id="user-following-stats">
		<a href="<%= followers_user_path %>">
			<strong id="followers-count"><%= @followers.count %></strong>
			Followers
		</a>
			|
		<a href="<%= followed_users_user_path %>">
			<strong id="followed-users-count"><%= @followed_users.count %></strong>
			Following
		</a>
	</div>
</div>
<hr>

app/views/users/followed_users.html.erb
<div class="user-following">
	<% content_for(:title) { "Following"} %>

	<div class="offset2">
		<h1>
			<% if @user == current_user %>
				You currently follow:
			<% else %>
				<%= @user.username %> is Following:
			<% end %>
		</h1>
	</div>

	<div class="row">
		<div class="span8 offset2 panel">
			<ul class="users-list">
				<%= render @followed_users %>
			</ul>
		</div>
	</div>
</div>

app/views/users/followers.html.erb
<div class="user-followers">
	<% content_for(:title) { "Followers"} %>
	<h1>
		<% if @user == current_user %>
			Your Followers
		<% else %>
			<%= @user.username %>'s Followers
		<% end %>
	</h1>

	<ul class="users-list">
		<%= render @followers %>
	</ul>

</div>

app/views/users/index.html.erb
<% content_for(:title) { "Users" } %>


<div class="offset2">
  <h1>
  	<%= "All Users" %>
  </h1>
</div>

<div class="row">
  <div class="span8 offset2 panel">
    <ul class="users-list">
    	<%=	render @users %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:title) { @user.username } %>

<div class="row">
  <div class="span12">
    <h1 class="profile-title">
    	<%= "#{@user.username}" %>
    </h1>
    <% if @user.tagline %>
      <p class="profile-tagline">
        "<em><%= "#{@user.tagline}" %></em>"
      </p>
    <% end %>
  </div>
</div>


<div class="row">
  <aside class="span3 panel">
    <div id="profile-pic">
      <%= image_tag("generic-profile-picture.png") %>
    </div>
    <hr />

    <%= render partial: 'user_following' %>

    <div id="my-trips">
      <h3>
        My <%= @trips.count %> Trips:
      </h3>
      <ul>
        <%= render @trips %>
      </ul>
      <hr>
    </div>

    <div id="my-contributorships">
      <h3>
        Member of:
      </h3>
      <ul>
        <%= render partial: 'trips/trip', collection: @trips_contributed_to %>
      </ul>
      <hr>
    </div>

  </aside>

  <div class="span8 panel">
    <h2>
      Trip Feed:
    </h2>

    <p><em>
      <% if current_user == @user %>
        You are
      <% else %>
        <%= @user.username %> is
      <% end %>
      currently subscribed to <strong><%= link_to @user.subscribed_trips.count, trip_subscriptions_user_path(@user) %></strong> trips
        <% if @user.trips %>
          (and <%= @user.trips.count %> of your own!)
        <% end %>
    </p></em>
    <hr>

    <% if current_user == @user && @user.subscribed_trips.size < 1 && @user.trips.size < 0 %>
      <h4>
        Follow <%= link_to "people", users_path %>,
         subscribe to <%= link_to "trips", trips_path %>,
         or <%= link_to "create your own", new_trip_path %>
         to see them appear in your feed!
      </h4>
    <% else %>
      <ul class="user-trip-feed">
        <%= render partial: "shared/feed_item", collection: @feed_items %>
      </ul>
    <% end %>
  </div>
</div>

app/views/users/trip_subscriptions.html.erb
<% content_for(:title) { "#{@user.username}'s Trip Subscriptions" } %>

<div class="offset2">
  <h1>
    <%= "#{@user.username}'s #{@subscriptions.count} Trip Subscriptions" %>
  </h1>
</div>

<div class="row">
  <div class="span8 offset2 panel">

    <div id="trip-subscriptions-list">

      <%= render @subscriptions %>

    </div>
  </div>
</div>