config/routes.rb
TripFollower2::Application.routes.draw do

  devise_for :users

  root to: 'static_pages#home'

  resources :users, only: [:index, :show] do
    resources :user_followings, only: [:create, :destroy]
    member do
      get :followed_users, :followers, :trip_subscriptions
      #get :trip_subscriptions
    end
  end

  resources :trips do
  	resources :trip_administratorings, only: [:create, :destroy]
    resources :trip_whitelistings, only: [:create, :destroy]
    member do
      get :subscribers
      post :subscribe
      delete :unsubscribe
    end
  end

  resources :events, except: [:new, :show]

  resources :instagrams, only: [:show, :index]

  resources :authorizations, only: [:index, :destroy]

  get 'auth/:provider/callback', to: "authorizations#create"
  get 'sandbox', to: 'static_pages#sandbox'
end

app/views/shared/_feed_item.html.erb
<% case feed_item[:media_type] %>
  <% when "instagram" %>
    <%= render partial: "shared/instagram",
        locals: { instagram: feed_item } %>
  <% when "tweet" %>
    <%= render partial: "shared/tweet",
        locals: { tweet: feed_item } %>
  <% when "tumble" %>
    <%= render partial: "shared/tumble",
        locals: { tumble: feed_item } %>
  <% when "flickr" %>
    <%= render partial: "shared/flickr",
        locals: { flickr: feed_item } %>
<% end %>

app/views/shared/_flickr.html.erb
<li class="flickr">

  <%= link_to flickr[:url] do %>
    <%= image_tag flickr[:url], alt: "Flickr photo by #{flickr[:owner]}", class: "flickr-img" %>
  <% end %>
  <%= "Created by #{flickr[:username]} at #{Time.at(flickr[:timestamp])}" %>
  <br>

</li>

app/views/shared/_following_buttons.html.erb
<!-- *** Be sure to pass in the proper user -->
<!-- *** Future: Pass in the button bootstrap classes *** -->
<% if current_user && current_user != user %>
  <% if current_user.following?(user) %>
    <div class="span2">
        <button class="unfollow btn-following btn btn-small btn-user-<%= user.id %>"
                data-url="<%= user_user_following_path(user, current_user) %>">Unfollow
        </button>
        <button class="follow btn btn-following btn-small btn-primary btn-user-<%= user.id %>"
                data-url="<%= user_user_followings_path(user) %>"
                style="display: none">
                Follow
        </button>
    </div>
  <% else %>
    <div class="span2">
        <button class="unfollow btn btn-following btn-small btn-user-<%= user.id %>"
                data-url="<%= user_user_following_path(user, current_user) %>"
                style="display: none">
                Unfollow
        </button>
        <button class="follow btn btn-following btn-small btn-primary btn-user-<%= user.id %>"
                data-url="<%= user_user_followings_path(user) %>">
                Follow
        </button>
    </div>
  <% end %>

    <%= javascript_tag do %>
        TF.UserFollowing.addFollowingListeners($("button.btn-user-<%= user.id %>"));
    <% end %>

<% end %>

app/views/shared/_instagram.html.erb
<li class="instagram-photo">

  <%= link_to instagram[:link] do %>
    <%= image_tag instagram[:low_res]["url"], alt: "Instagram Photo by #{instagram[:username]}" %>
  <% end %>
  <%= "Created by #{instagram[:username]} at #{Time.at(instagram[:timestamp])}" %>

</li>

app/views/shared/_instagram_photo.html.erb
<li class="instagram-photo">

  <%= link_to instagram_photo[:link] do %>
    <%= image_tag instagram_photo[:low_res]["url"], alt: "Instagram Photo by #{instagram_photo[:username]}" %>
  <% end %>

</li>

app/views/shared/_trip_subscribe_buttons.html.erb
<!-- *** Be sure to pass in the proper trip -->
<!-- *** Future: Pass in the button bootstrap classes *** -->
<% if current_user && trip.creator != current_user %>
  <% if current_user.subscribed_to?(trip) %>
    <div class="span2">
      <button class="unsubscribe btn-subscription btn btn-small btn-trip-<%= trip.id %>"
              data-url="<%= unsubscribe_trip_path(trip) %>">Unsubscribe
      </button>
      <button class="subscribe btn-subscription btn-primary btn btn-small btn-trip-<%= trip.id %>"
              data-url="<%= subscribe_trip_path(trip) %>"
              style="display: none"> <!-- << Here's the difference -->
              Subscribe
      </button>
    </div>
  <% else %>
    <div class="span2">
      <button class="unsubscribe btn btn-subscription btn-small btn-trip-<%= trip.id %>"
              data-url="<%= unsubscribe_trip_path(trip) %>"
              style="display: none"> <!-- << Here's the difference -->
              Unsubscribe
      </button>
      <button class="subscribe btn btn-subscription btn-small btn-primary btn-trip-<%= trip.id %>"
              data-url="<%= subscribe_trip_path(trip) %>">
              Subscribe
      </button>
    </div>
  <% end %>


  <%= javascript_tag do %>
    TF.Trip.addSubscriptionListeners($("button.btn-trip-<%= trip.id %>"));
  <% end %>

<% else %>

  <div class="span2"><button class="btn btn-small btn-subscription btn-sneaky"></button></div>

<% end %>

app/views/shared/_trip_subscriber_stats.html.erb
<span class="trip-subscriber-stats">
  <%= link_to raw("<span class='trip-subscriber-count' data-url='#{ subscribers_trip_path(trip)}' data-id='#{trip.id}'>#{trip.subscribed_users.count}</span> subscribers"), 
  		subscribers_trip_path(trip), 
  		class: "trip-subscriber-stats" %>
</span>

app/views/shared/_tumble.html.erb
<li class="tumble">

  <% case tumble[:type] %>
  <% when "text" %>
    <div class="tumble-text">
      <strong><%= tumble[:title] %></strong>
      <p><%= tumble[:body].html_safe %></p>
      <hr>
      <span class="author">
        <%= "Created by #{tumble[:blog_name]} at #{Time.at(tumble[:timestamp])}" %>
      </span>
    </div>
  <% when "photo" %>
    <a href="<%= tumble[:url] %>">
      <img src = "<%= tumble[:image_url] %>" alt="Tumble Image by <%= tumble[:blog_name] %>", class="tumblr-img">
    </a>
    <p class="author">
      <%= "Created by #{tumble[:blog_name]} at #{Time.at(tumble[:timestamp])}" %>
    </p>
  <% else %>
    <p class="author">
      <%= "#{tumble[:type]} created by #{tumble[:blog_name]} at #{Time.at(tumble[:timestamp])}" %>
    </p>
  <% end %>


</li>

app/views/shared/_tweet.html.erb
<li class="tweet">

<!--   <%= image_tag tweet[:user_image], alt: "#{tweet[:username]}" %>
  <%= "#{tweet[:username]} said (at #{Time.at(tweet[:timestamp])}):"%>
  <%= tweet[:text] %> -->
  <%= Tweet.oembed(tweet[:id])["html"].html_safe %>

</li>