config/routes.rb
TripFollower2::Application.routes.draw do

  devise_for :users

  root to: 'static_pages#home'

  resources :users, only: [:index, :show] do
    resources :user_followings, only: [:create, :destroy]
    member do
      get :followed_users, :followers, :trip_subscriptions
      #get :trip_subscriptions
    end
  end

  resources :trips do
  	resources :trip_administratorings, only: [:create, :destroy]
    resources :trip_whitelistings, only: [:create, :destroy]
    member do
      get :subscribers
      post :subscribe
      delete :unsubscribe
    end
  end

  resources :events, except: [:new, :show]

  resources :instagrams, only: [:show, :index]

  resources :authorizations, only: [:index, :destroy]

  get 'auth/:provider/callback', to: "authorizations#create"
  get 'sandbox', to: 'static_pages#sandbox'
end

app/views/layouts/_footer.html.erb
<div id="footer" class="navbar navbar-bottom navbar-inverse">
	<div class="container-wide">
		<div class="container-normal">
			<footer class="footer">
			  Created by Erik Trautman
			</footer>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Trip Follower", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Trips", trips_path %></li>
          <% if user_signed_in? %>
          	<li><%= link_to "My Page", user_path(current_user)%></li>
            <li><%= link_to "New Trip", new_trip_path %></li>
	          <li id="fat-menu" class="dropdown">
	            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	              Account <b class="caret"></b>
	            </a>
	            <ul class="dropdown-menu">
                <li class="pad-a"><%= current_user.username %></li>
                <li class="divider"></li>
                <li><%= link_to "Link Media Accounts",
                  authorizations_path %></li>
                <li><%= link_to "Trip Subscriptions", trip_subscriptions_user_path(current_user) %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
	              <li class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
	            </ul>
	          </li>
	        <% else %>
	        	<li><%= link_to "Sign In", user_session_path %></li>
	        <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
    	<%=full_title(yield(:title))%>
    </title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
  	<div class = "container body" id="body">
  		<% flash.each do |key, value| %>
  			<div class="alert alert-<%= key %>"><%= value %></div>
  		<% end %>

<!--       <p class='notice'><%= notice %> via Devise?</p>
      <p class='alert'><%= alert %> via Devise?</p> -->

  		<%= yield %>

<!--        <div class="debug">
        <br><br><br><br><br><br>
        <%= debug(params) if Rails.env.development? %>
        <%= debug(session) if Rails.env.development? %>
      </div> -->


    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>